function CUR_metaRun_training_testing
% This script will just run a specific loop, and then run another one after
% the first is done. I made this just so I didn't have to run it manually.
% Running both at the same time took up too much memory.
dbstop if error;

%% Training C2
% trainingTic = tic;
% display('Starting training');
% CUR_runAnnulusExpt2('annulusExptFixedContrast/simulation4/training/facesLoc.mat',...
%                     'annulusExptFixedContrast/simulation4/training/data/patchSet_3x2/lfwSingle50000',...
%                     'annulusExptFixedContrast/simulation4/training/',...
%                     50000,6250,1,4,...
%                     1659,237,8,...
%                     'patchSet_3x2',...
%                     0,1067,0)
% display('Ended training');
% trainingToc = toc(trainingTic)

%% Training localization
% trainingLocTic = tic;
% display('Starting training loc');
% CUR_genLoc('annulusExptFixedContrast/simulation4/training/',50000,2000,1)
% trainingLocToc = toc(trainingLocTic);
% display('Ended training loc');

%% Testing C2
testingTic = tic;
display('Starting testing');
CUR_runAnnulusExpt2('annulusExptFixedContrast/simulation4/testing/facesLoc.mat',...
                    'annulusExptFixedContrast/simulation4/testing/data/patchSet_3x2/lfwSingle50000',...
                    'annulusExptFixedContrast/simulation4/testing/',...
                    25000,6250,[],[],...
                    1000,200,7,...
                    'patchSet_3x2',...
                    0,1067,0)
display('Ended testing');
testingToc = toc(testingTic);

%% Testing localization
testingLocTic = tic;
display('Starting testing loc');
CUR_genLoc('annulusExptFixedContrast/simulation4/testing/',25000,2500,1)
testingLocToc = toc(testingLocTic);
display('Ended testing loc');


end



% CUR_runAnnulusExpt2('annulusExptFixedContrast/simulation4/training/facesLoc.mat',...
%                     'annulusExptFixedContrast/simulation4/training/data/patchSet_3x2/lfwSingle50000/smallRun',...
%                     'annulusExptFixedContrast/simulation4/training/',...
%                     5000,1000,1,5,...
%                     1659,237,8,...
%                     'patchSet_3x2',...
%                     0,1067,0)
